# -*- coding: utf-8 -*-
"""car_Linearreggresion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18htwSq4TXtXyhBQSINCQacqduAWx3my9

#یه پروژه که از کگل پیدا کردم و روش کار کردم در مورد پیشبینی کردن قیمت ماشین که چند تا فیچر هست از طریق اونها مدل ترین میشه.
#data set :car details v4
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

File_path = '/content/car details v4.csv'
car_ = pd.read_csv(File_path, low_memory=False)
car_.dropna(inplace=True)
car_.reset_index(drop=True, inplace=True)
car_

car_.info()

car_['Height'].isna().sum() / 2059*100

car = car_[['Price','Year','Kilometer','Owner']]

car

car.describe()

car.reset_index(inplace=True, drop=True)

plt.figure(figsize=(10,5))
# plt.ylim(10000)
# plt.xlim(10000)
sns.scatterplot(data=car, x='Kilometer', y='Price',alpha=0.3)

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

for owner in car['Owner']:
  if owner == 'First':
    car['Owner'] = car['Owner'].replace(owner, 1)
  elif owner == 'Second':
    car['Owner'] = car['Owner'].replace(owner, 2)
  elif owner == 'Third':
    car['Owner'] = car['Owner'].replace(owner, 3)
  elif owner == 'UnRegistered Car':
    car['Owner'] = car['Owner'].replace(owner, 4)

car['Owner']

y = np.asarray(car['Price'])
X = np.asarray(car[['Year','Kilometer']])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

LNR = LinearRegression()
LNR.fit(X_train, y_train)

y_pred = LNR.predict(X_test)

y_pred

y_test

plt.scatter(y_test, y_pred, alpha=0.3);
plt.plot(np.linspace(0, 45, 100),
         np.linspace(0, 45, 100),
         c='green')

plt.xlabel('Y True')
plt.ylabel('Y Predict');

car.describe()

lr2 = LinearRegression(fit_intercept=False)
lr2.fit(X_train, y_train)

y_pred = lr2.predict(X_test)

plt.scatter(y_test, y_pred, alpha=0.4);
plt.plot(np.linspace(0, 45, 100),
         np.linspace(0, 45, 100),
         c='red')

plt.xlabel('Y True')
plt.ylabel('Y Predict');

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, random_state=0)

# Model selection (example: using Ridge regression)
lr_ridge = Ridge(alpha=1.0)  # Experiment with different alpha values
lr_ridge.fit(X_train, y_train)

# Prediction and evaluation
y_pred = lr_ridge.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

plt.figure(figsize=(10,10))  # Adjust plot size
sns.scatterplot(x=y_test,y=y_pred,
                alpha=0.4, color='blue', marker='o')  # Customize markers, color, and transparency
sns.regplot(x=y_test, y=y_pred, color='red', scatter=False)  # Add regression line

plt.title("Car Price vs. Kilometers Driven")  # Add title
plt.xlabel("Kilometers Driven (km)")  # Add x-axis label
plt.ylabel("Price (USD)")  # Add y-axis label
plt.grid(True, linestyle='--', alpha=0.5)  # Add gridlines
plt.gca().set_facecolor('lightgray')  # Set background color



plt.show()

from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline

steps = [(('poly_feature'), PolynomialFeatures(degree=2)),
         ('lr', LinearRegression(fit_intercept=False))]
model = Pipeline(steps=steps)
model.fit(X_train, y_train)

model['lr'].coef_

y_pred = model.predict(X_test)
plt.figure(figsize=(10,10))  # Adjust plot size
sns.scatterplot(x=y_test,y=y_pred,
                alpha=0.4, color='blue', marker='o')  # Customize markers, color, and transparency
sns.regplot(x=y_test, y=y_pred, color='red', scatter=False)  # Add regression line

plt.title("Car Price vs. Kilometers Driven")  # Add title
plt.xlabel("Kilometers Driven (km)")  # Add x-axis label
plt.ylabel("Price (USD)")  # Add y-axis label
plt.grid(True, linestyle='--', alpha=0.5)  # Add gridlines
plt.gca().set_facecolor('lightgray')  # Set background color

steps = [('poly_feature', PolynomialFeatures(degree=2)),
         ('lr', Ridge(alpha=100, fit_intercept=False))]
lr_ridge = Pipeline(steps=steps)
lr_ridge.fit(X_train, y_train)
y_pred = lr_ridge.predict(X_test)

plt.figure(figsize=(10,10))  # Adjust plot size
sns.scatterplot(x=y_test,y=y_pred,
                alpha=0.4, color='blue', marker='o')  # Customize markers, color, and transparency
sns.regplot(x=y_test, y=y_pred, color='red', scatter=False)  # Add regression line

plt.title("Car Price vs. Kilometers Driven")  # Add title
plt.xlabel("Kilometers Driven (km)")  # Add x-axis label
plt.ylabel("Price (USD)")  # Add y-axis label
plt.grid(True, linestyle='--', alpha=0.5)  # Add gridlines
plt.gca().set_facecolor('lightgray')  # Set background color

steps = [('poly_feature', PolynomialFeatures(degree=5)),
         ('lr', Lasso(alpha=100, fit_intercept=False))]
lr_lasso = Pipeline(steps=steps)
lr_lasso.fit(X_train, y_train)

y_pred = lr_lasso.predict(X_test)

plt.figure(figsize=(10,10))  # Adjust plot size
sns.scatterplot(x=y_test,y=y_pred,
                alpha=0.4, color='blue', marker='o')  # Customize markers, color, and transparency
sns.regplot(x=y_test, y=y_pred, color='red', scatter=False)  # Add regression line

plt.title("Car Price vs. Kilometers Driven")  # Add title
plt.xlabel("Kilometers Driven (km)")  # Add x-axis label
plt.ylabel("Price (USD)")  # Add y-axis label
plt.grid(True, linestyle='--', alpha=0.5)  # Add gridlines
plt.gca().set_facecolor('lightgray')  # Set background color

steps = [('poly_feature', PolynomialFeatures(degree=3)),
         ('lr', ElasticNet(alpha=100, fit_intercept=False))]
lr_elastic = Pipeline(steps=steps)
lr_elastic.fit(X_train, y_train)
y_pred = lr_elastic.predict(X_test)

plt.figure(figsize=(10,10))  # Adjust plot size
sns.scatterplot(x=y_test,y=y_pred,
                alpha=0.4, color='blue', marker='o')
sns.regplot(x=y_test, y=y_pred, color='red', scatter=False)

plt.title("Car Price vs. Kilometers Driven")
plt.xlabel("Kilometers Driven (km)")
plt.ylabel("Price (USD)")

from sklearn.metrics import max_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import r2_score



print(max_error(y_true=y_test, y_pred=LNR.predict(X_test)))
print(mean_absolute_error(y_true=y_test, y_pred=LNR.predict(X_test)))
print(mean_squared_error(y_true=y_test, y_pred=LNR.predict(X_test)))
print(root_mean_squared_error(y_true=y_test, y_pred=LNR.predict(X_test)))
print(r2_score(y_true=y_test, y_pred= LNR.predict(X_test)))

print(max_error(y_true=y_test, y_pred=lr_ridge.predict(X_test)))
print(mean_absolute_error(y_true=y_test, y_pred=lr_ridge.predict(X_test)))
print(mean_squared_error(y_true=y_test, y_pred=lr_ridge.predict(X_test)))
print(root_mean_squared_error(y_true=y_test, y_pred=lr_ridge.predict(X_test)))
print(r2_score(y_true=y_test, y_pred= lr_ridge.predict(X_test)))

print(max_error(y_true=y_test, y_pred=lr_lasso.predict(X_test)))
print(r2_score(y_true=y_test, y_pred=lr_lasso.predict(X_test)))

print(max_error(y_true=y_test, y_pred=lr_elastic.predict(X_test)))
print(r2_score(y_true=y_test, y_pred=lr_elastic.predict(X_test)))

