# -*- coding: utf-8 -*-
"""car_kernel regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1waPqMIAQXkXe-YKq3K7EPNgnQsDcx7yE
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as ticker

file_path = '/content/car details v4.csv'
car = pd.read_csv(file_path)
car.head()

car.info()

car = car[['Kilometer', 'Price', 'Year']]

car

car.dropna()

car.reset_index()

car.describe()

mu = car['Kilometer'].mean()
std = car['Kilometer'].std()

Z = np.abs((car['Kilometer'] - mu)/std)

print(car[Z>3].shape[0]/car.shape[0]*100)

car = car[Z<=3]

mu = car['Price'].mean()
std = car['Price'].std()

Z = np.abs((car['Price'] - mu)/std)

print(car[Z>3].shape[0]/car.shape[0]*100)

car = car[Z<=3]

mu = car['Year'].mean()
std = car['Year'].std()

Z = np.abs((car['Year'] - mu)/std)

print(car[Z>3].shape[0]/car.shape[0]*100)

car = car[Z<=3]

X = np.array(car['Price'])
y = np.array(car['Kilometer'])
plt.figure(figsize=(10,6))
plt.scatter(X,y)
plt.gca().yaxis.set_major_formatter(ticker.StrMethodFormatter('{x:,.0f}'))
plt.gca().xaxis.set_major_formatter(ticker.StrMethodFormatter('{x:,.0f}'))
plt.show()

from scipy.spatial.distance import cdist
def gaussian_kernel(u, h):
    return np.exp(-0.5 * (u / h) ** 2) / (h * np.sqrt(2 * np.pi))

# Implement kernel regression
def kernel_regression(X, y, X_test, h):
    y_pred = np.zeros(X_test.shape[0])
    for i, x in enumerate(X_test):
        weights = gaussian_kernel(cdist([x], X), h)
        y_pred[i] = np.sum(weights * y) / np.sum(weights)
    return y_pred

from sklearn.model_selection import train_test_split
X = np.asarray(car[['Kilometer', 'Year']])
y = np.asarray(car['Price'])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

h = 0.1
y_pred = kernel_regression(X_train, y_train, X_test, h)
X_test_for_plot = X_test[:, 0]

plt.figure(figsize=(10, 6))
plt.scatter(X_train[:, 0], y_train, color='blue', label='Data points')
plt.plot(X_test, y_pred, color='red', label='Gaussian Kernel Regression')
plt.xlabel('Kilometer')
plt.ylabel('Price')
plt.title('Gaussian Kernel Regression')
plt.legend()
plt.show()

