# -*- coding: utf-8 -*-
"""Copy of Admission_predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s-k2WF-7W0pcZ_4QnZx4y8nb1IpYVCNz

# پروژه یه دیتاستی هست که دانشجویانی که شانس قبولی دارن رو مشخص میکنه .
#*دیتا ست توی فایل هست
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

File = pd.read_csv('/content/Admission_Predict_Ver1.1.csv', low_memory=False)
File.head()
File

File.info()

File.describe()

y = File['Chance of Admit ']
File.drop(['Serial No.','Chance of Admit '],axis=1, inplace=True)
X = File

mu = File['GRE Score'].mean()
std = File['GRE Score'].std()
Z = np.abs((File['GRE Score'] - mu)/std)

print(File[Z>3].shape[0]/File.shape[0]*100)

File = File[Z<=3]

mu = File['TOEFL Score'].mean()
std = File['TOEFL Score'].std()
Z = np.abs((File['TOEFL Score']- mu)/std)
print(File[Z>3].shape[0]/File.shape[0]*100)

File = File[Z<=3]

mu = File['SOP'].mean()
std = File['SOP'].std()
Z = np.abs((File['SOP'] - mu)/std)

print(File[Z>3].shape[0]/File.shape[0]*100)

File = File[Z<=3]

mu = File['University Rating'].mean()
std = File['University Rating'].std()
Z = np.abs((File['University Rating'] - mu)/std)

print(File[Z>3].shape[0]/File.shape[0]*100)

File = File[Z<=3]

File

y

from sklearn.model_selection import train_test_split

X = np.array(File)
y = np.array(y)

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

from sklearn.linear_model import LinearRegression
lr1 = LinearRegression()
lr1.fit(X_train,y_train)
lr2 = LinearRegression(fit_intercept = False)
lr2.fit(X_test,y_test)

lr1.coef_

lr1.intercept_

y_pred1 = lr1.predict(X_test)
y_pred2 = lr2.predict(X_test)

y_pred1

fig, axes = plt.subplots(1, 2, figsize=(12, 7))

axes[0].scatter(y_test, y_pred1, alpha=0.3)
axes[0].plot(np.linspace(0, 45, 100), np.linspace(0, 45, 100), c='green')
axes[0].set_xlim(0, 1)
axes[0].set_ylim(0, 1)
axes[0].set_xlabel('Y True')
axes[0].set_ylabel('Y Pred')
axes[0].set_title('Y True vs Y Pred (Model 1)')

axes[1].scatter(y_test, y_pred2, alpha=0.3)
axes[1].plot(np.linspace(0, 45, 100), np.linspace(0, 45, 100), c='green')
axes[1].set_xlim(0, 1)
axes[1].set_ylim(0, 1)
axes[1].set_xlabel('Y True')
axes[1].set_ylabel('Y Pred')
axes[1].set_title('Y True vs Y Pred (Model 2)')


plt.tight_layout()
plt.show()

from sklearn.preprocessing import PolynomialFeatures

pf = PolynomialFeatures(degree=3)
X_train_pf = pf.fit_transform(X_train)

lr_pf = LinearRegression(fit_intercept=False)
lr_pf.fit(X_train_pf, y_train)

y_pred = lr_pf.predict(PolynomialFeatures(degree=3).fit_transform(X_test))

plt.scatter(y_test, y_pred, alpha=0.4);
plt.plot(np.linspace(0, 45, 100),
         np.linspace(0, 45, 100),
         c='red')
plt.xlim(0,1)
plt.ylim(0,1)
plt.xlabel('Y True')
plt.ylabel('Y Predict');

from sklearn.pipeline import Pipeline

steps = [('poly_feature', PolynomialFeatures(degree=15)),
         ('lr1', LinearRegression(fit_intercept=False))]

model = Pipeline(steps=steps)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

plt.scatter(y_test, y_pred, alpha=0.4);
plt.plot(np.linspace(0, 45, 100),
         np.linspace(0, 45, 100),
         c='green')
plt.xlim(0,1)
plt.ylim(-10,10)
plt.xlabel('Y True')
plt.ylabel('Y Predict');

from sklearn.linear_model import Ridge, Lasso, ElasticNet

steps = [('poly_feature', PolynomialFeatures(degree=5)),
         ('lr1', LinearRegression(fit_intercept=False))]

lr1 = Pipeline(steps=steps)

lr1.fit(X_train, y_train)

steps=[('poly_feature', PolynomialFeatures(degree=5)),
      ('lr1', Ridge(alpha=100, fit_intercept=False))]
lr1_ridge = Pipeline(steps=steps)
lr1_ridge.fit(X_train, y_train)
y_pred = lr1_ridge.predict(X_test)

plt.scatter(y_test, y_pred, alpha=0.4);
plt.plot(np.linspace(0,45,100),
         np.linspace(0,45,100),
         c='green')

plt.xlim(0,1)
plt.ylim(0,1)
plt.xlabel('Y True')
plt.ylabel('Y Predict');

steps = [('poly_feature', PolynomialFeatures(degree=5)),
         ('lr1', Lasso(alpha=1,fit_intercept=False))]

lr1_lasso = Pipeline(steps=steps)

lr1_lasso.fit(X_train, y_train)
y_pred = lr1_lasso.predict(X_test)

plt.scatter(y_test, y_pred, alpha=0.5);
plt.plot(np.linspace(0,45,100),
         np.linspace(0,45,100),
         c='red')

plt.xlim(0,1)
plt.ylim(0,1)
plt.xlabel('Y True')
plt.ylabel('Y Predict');

steps = [('poly_feature', PolynomialFeatures(degree=5)),
         ('lr1', ElasticNet(alpha=1, l1_ratio=0.5, fit_intercept=False))]
lr1_elastik = Pipeline(steps=steps)
lr1_elastik.fit(X_train, y_train)
y_pred = lr1_elastik.predict(X_test)

plt.scatter(y_test, y_pred, alpha=0.4);
plt.plot(np.linspace(0, 45, 100),
         np.linspace(0, 45, 100),
         c='red')
plt.xlim(0,1)
plt.ylim(0,1)
plt.xlabel('Y True')
plt.ylabel('Y Predict');

from sklearn.metrics import max_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import r2_score

print(max_error(y_true=y_test, y_pred=lr1.predict(X_test)))
print(max_error(y_true=y_test, y_pred=lr1_ridge.predict(X_test)))
print(max_error(y_true=y_test, y_pred=lr1_lasso.predict(X_test)))
print(max_error(y_true=y_test, y_pred=lr1_elastik.predict(X_test)))

print(mean_absolute_error(y_true=y_test, y_pred=lr1.predict(X_test)))
print(mean_absolute_error(y_true=y_test, y_pred=lr1_ridge.predict(X_test)))
print(mean_absolute_error(y_true=y_test, y_pred=lr1_lasso.predict(X_test)))
print(mean_absolute_error(y_true=y_test, y_pred=lr1_elastik.predict(X_test)))

print(mean_squared_error(y_true=y_test, y_pred=lr1.predict(X_test)))
print(mean_squared_error(y_true=y_test, y_pred=lr1_ridge.predict(X_test)))
print(mean_squared_error(y_true=y_test, y_pred=lr1_lasso.predict(X_test)))
print(mean_squared_error(y_true=y_test, y_pred=lr1_elastik.predict(X_test)))

print(root_mean_squared_error(y_true=y_test, y_pred=lr1.predict(X_test)))
print(root_mean_squared_error(y_true=y_test, y_pred=lr1_ridge.predict(X_test)))
print(root_mean_squared_error(y_true=y_test, y_pred=lr1_lasso.predict(X_test)))
print(root_mean_squared_error(y_true=y_test, y_pred=lr1_elastik.predict(X_test)))

print(r2_score(y_true=y_test, y_pred=lr1.predict(X_test)))
print(r2_score(y_true=y_test, y_pred=lr1_ridge.predict(X_test)))
print(r2_score(y_true=y_test, y_pred=lr1_lasso.predict(X_test)))
print(r2_score(y_true=y_test, y_pred=lr1_elastik.predict(X_test)))

https://github.com/Mrga637/Main_projects.git