# -*- coding: utf-8 -*-
"""Copy of uber.-.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19e63Pi9h_RgwpXR1zl4cwQbOlqpBRdhR
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

data = pd.read_csv('/content/uber.csv', low_memory = False , index_col= 0)
data

data.info()

data.dropna(inplace=True)

data.describe()

Q1 = data['pickup_longitude'].quantile(0.25)
Q3 = data['pickup_longitude'].quantile(0.75)
IQR = Q3 - Q1
min = Q1 - 1.5 * IQR
max = Q3 + 1.5 *IQR

data[(data['pickup_longitude']<min) | (data['pickup_longitude']>max)].shape[0]/data.shape[0]

mu = data['pickup_longitude'].mean()
std = data['pickup_longitude'].std()
Z = np.abs((data['pickup_longitude'] - mu)/std)
print(data[Z>3].shape[0]/data.shape[0]*100)
data = data[Z<=3]

mu = data['pickup_latitude'].mean()
std = data['pickup_latitude'].std()
Z = np.abs((data['pickup_latitude'] - mu)/std)
print(data[Z>3].shape[0]/data.shape[0]*100)
data = data[Z<=3]

mu = data['dropoff_latitude'].mean()
std = data['dropoff_latitude'].std()
Z = np.abs((data['dropoff_latitude'] - mu)/std)
print(data[Z>3].shape[0]/data.shape[0]*100)
data = data[Z<=3]

mu = data['dropoff_longitude'].mean()
std = data['dropoff_longitude'].std()
Z = np.abs((data['dropoff_longitude'] - mu)/std)
print(data[Z>3].shape[0]/data.shape[0]*100)
data = data[Z<=3]

data.reset_index(drop=True, inplace= True)

data.describe()

from geopy.distance import geodesic as gp
Distance = []
for i in range(data.shape[0]):
  start = (data.loc[i, 'pickup_latitude'], data.loc[i, 'pickup_longitude'])
  dest= (data.loc[i, 'dropoff_latitude'], data.loc[i, 'dropoff_longitude'])
  Distance.append(gp(start, dest).kilometers)

from collections.abc import ValuesView
df = pd.DataFrame({'distance': Distance,
                   'n_passenger': data['passenger_count'].values,
                   'fare': data['fare_amount'].values})

df

df.describe()

df = df[df['distance']!=0]
df = df[df['fare']>0]
df = df[df['n_passenger']<=6]
df = df[df['n_passenger']!=0]
df.reset_index(inplace = True, drop=True)

mu = df['fare'].mean()
std = df['fare'].std()
Z = np.abs((df['fare']-mu)/std)

print(df[Z>3].shape[0]/df.shape[0]*100)
df = df[Z<=3]

mu = df['distance'].mean()
std = df['distance'].std()
Z = np.abs((df['distance']-mu)/std)
print(df[Z>3].shape[0]/df.shape[0]*100)
df = df[Z<=3]

df.reset_index(inplace = True, drop = True)

sns.scatterplot(x='distance', y='fare', data=df,alpha=0.3)

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

x = np.array(df[['distance','n_passenger']])
y = np.array(df['fare'])

x_train, x_test, y_train, y_test = train_test_split(x,y ,test_size=0.35)

print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

tetha1 = np.linalg.inv(x_train.T @ x_train) @ x_train.T @ y_train

tetha1

x_test @ tetha1

xx = np.c_[np.ones((x_train.shape[0])), x_train]

tetha2 = np.linalg.inv(xx.T @ xx) @ xx.T @ y_train

tetha2

lr1= LinearRegression()
lr1.fit(x_train, y_train)

lr1.coef_

lr1.intercept_

tetha2

y_pred = lr1.predict(x_test)

y_pred

y_test

plt.scatter(y_test, y_pred, alpha=0.4)
plt.plot(np.linspace(0,45,100),
         np.linspace(0,45,100),
         c='red')
plt.xlabel('Y True')
plt.ylabel('Y pred');

lr2 = LinearRegression(fit_intercept=False)
lr2.fit(x_train, y_train)

lr2.coef_

tetha1

y_pred = lr2.predict(x_test)

plt.scatter(y_test, y_pred, alpha=0.4);
plt.plot(np.linspace(0,45,100),
        np.linspace(0,45,100),
        c='red')
plt.xlabel('Y True')
plt.ylabel('Y pred');

from sklearn.metrics import max_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import r2_score

max_error(y_true=y_test, y_pred=y_pred)

mean_absolute_error(y_true=y_test, y_pred=y_pred)

mean_squared_error(y_true=y_test, y_pred=y_pred)

root_mean_squared_error(y_true=y_test, y_pred=y_pred)

r2_score(y_true=y_test, y_pred=y_pred)

"""polynimal Feutures

"""

from sklearn.preprocessing import PolynomialFeatures

pf = PolynomialFeatures(degree = 2)
x_train_pf = pf.fit_transform(x_train)

lr_pf = LinearRegression(fit_intercept=False)
lr_pf.fit(x_train_pf, y_train)

lr_pf.coef_

lr_pf.intercept_

y_pred = lr_pf.predict(PolynomialFeatures(degree=2).fit_transform(x_test))

y_pred

plt.scatter(y_test, y_pred, alpha=0.4);
plt.plot(np.linspace(0,45,100),
         np.linspace(0,45,100),
         c='red')
plt.xlabel('Y true')
plt.ylabel('Y pred')

from sklearn.pipeline import Pipeline

steps = [('poly_feature', PolynomialFeatures(degree=15)),
         ('lr', LinearRegression(fit_intercept=False))]
model = Pipeline(steps=steps)
model.fit(x_train, y_train)

model['lr'].coef_;

y_pred = model.predict(x_test)

plt.scatter(y_test, y_pred, alpha=0.4);
plt.plot(np.linspace(0,45,100),
         np.linspace(0,45,100),
         c='red')
plt.xlabel('Ytrue')
plt.ylabel('Ypred')