# -*- coding: utf-8 -*-
"""final_pro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R0uLt8XHrZx4fKN2F7gdSwY_i_SKhLfc

#این پروژه فاینال بود برای یک بوت کمپ از سمت دانشگاه تهران
"""

import numpy as np
import pandas as pd
path_file = '/content/exportall 2009 - 2025.csv'
df = pd.read_csv(path_file)
df.drop(index=[0,1,2], axis=0, inplace=True)
df.drop('Department of Commerce',axis=1,inplace=True)

column_mapping = {}

# for year in range(2008, 2025):
#     unnamed_index = (year - 2008) * 2 + 2
#     column_mapping[f'Unnamed: {unnamed_index}'] = f'Year_{year}_{year + 1}'

# for key, value in column_mapping.items():
#     print(f"'{key}': '{value}',")# for writing down easier

df.reset_index(drop=True, inplace=True)
df.rename(columns={
'Unnamed: 1': 'Country',
'Unnamed: 2': 'Year_2008_2009',
'Unnamed: 4': 'Year_2009_2010',
'Unnamed: 6': 'Year_2010_2011',
'Unnamed: 8': 'Year_2011_2012',
'Unnamed: 10': 'Year_2012_2013',
'Unnamed: 12': 'Year_2013_2014',
'Unnamed: 14': 'Year_2014_2015',
'Unnamed: 16': 'Year_2015_2016',
'Unnamed: 18': 'Year_2016_2017',
'Unnamed: 20': 'Year_2017_2018',
'Unnamed: 22': 'Year_2018_2019',
'Unnamed: 24': 'Year_2019_2020',
'Unnamed: 26': 'Year_2020_2021',
'Unnamed: 28': 'Year_2021_2022',
'Unnamed: 30': 'Year_2022_2023',
'Unnamed: 32': 'Year_2023_2024',
'Unnamed: 34': 'Year_2024_2025',

},inplace=True)

not_needed_col = []
for not_ in range(3,37,2):
  not_needed_col.append(f'Unnamed: {not_}')
df.drop(not_needed_col, axis=1, inplace=True)

for year in range(2008, 2025):
    column_name = f'Year_{year}_{year + 1}'

    if column_name in df.columns:
        df[column_name] = pd.to_numeric(df[column_name].str.replace(',', ''), errors='coerce')
        df[column_name] = pd.to_numeric(df[column_name], errors='ignore')
df.dropna(inplace=True)
print(df.isnull().sum())

rows_to_check = df.index[1:]
for row in rows_to_check:
    row_values = df.loc[row, df.columns[1:]]
    Q1 = row_values.quantile(0.25)
    Q3 = row_values.quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    median_value = row_values.median()
    for col in df.columns[1:]:
        if df.at[row, col] < lower_bound or df.at[row, col] > upper_bound:
            df.at[row, col] = median_value

# pd.options.display.max_rows = 500
year_columns = df.columns[1:].tolist()
summary_stats = pd.DataFrame({
    'Year': year_columns,
    'Sum': df[year_columns].sum(),
    'Mean': df[year_columns].mean(),
    'Median': df[year_columns].median()
})
import matplotlib.pyplot as plt

years = np.array(summary_stats['Year'])
sum_values = np.array(summary_stats['Sum'])
mean_values = np.array(summary_stats['Mean'])
median_values = np.array(summary_stats['Median'])

plt.figure(figsize=(10, 5))
plt.plot(years, sum_values, label='Sum', marker='o', color='blue')
plt.plot(years, mean_values, label='Mean', marker='s', color='orange')
plt.plot(years, median_values, label='Median', marker='^', color='green')

plt.title('Summary Statistics Over Years')
plt.xlabel('Year')
plt.ylabel('Value')
plt.xticks(rotation=45)
plt.legend()

if np.any(mean_values < 1e6) and np.any(median_values < 1e6):
    plt.yscale('log')
plt.tight_layout()

plt.show()

summary_stats

df.set_index('Country', inplace=True)
top_10_exporters = {}
for year in df.columns[1:]:
    top_10_exporters[year] = df[year].nlargest(10).index.tolist()

print("Top 10 Exporting Countries by Year:")
for year, countries in top_10_exporters.items():
    print(f"{year}: {countries}")

growth_rate_df = df.pct_change(axis=1) * 100
growth_rate_df.columns = [f'Growth_{year}' for year in growth_rate_df.columns]
combined_df = pd.concat([df, growth_rate_df], axis=1)

print("\nCombined DataFrame with Growth Rates:")
print(combined_df)

most_recent_growth = growth_rate_df.iloc[:, -1]
highest_growth_countries = most_recent_growth.nlargest(10)
print("\nCountries with the Highest Growth Rate in the Most Recent Year:")
print(highest_growth_countries)

def bar_chart(selected_year):
    plt.figure(figsize=(10, 6))
    top_10 = df[selected_year].nlargest(10)
    top_10.plot(kind='bar', color='skyblue')
    plt.title(f'Top 10 Exporting Countries in {selected_year}')
    plt.xlabel('Country')
    plt.ylabel('Export Value')
    plt.xticks(rotation=45)
    plt.grid(axis='y', linestyle='--')
    plt.tight_layout()
    plt.show()

# Call the function for a specific year, e.g., 2022
bar_chart('Year_2008_2009')

def line_chart(selected_countries):
    plt.figure(figsize=(12, 8))
    df.loc[selected_countries].T.plot(marker='o')
    plt.title('Export Trends Over Time')
    plt.xlabel('Year')
    plt.ylabel('Export Value')
    plt.legend(title='Country', loc='upper left')
    plt.grid()
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

# Call the function with selected countries, e.g., USA and China
line_chart(['AFGHANISTAN', 'GERMANY'])

import seaborn as sns

def heatmap_correlation():
    # Compute the correlation matrix
    corr = df.corr()

    plt.figure(figsize=(15,10 ))
    sns.heatmap(corr, annot=True, cmap='coolwarm', fmt='.2f', linewidths=.5, square=True)
    plt.title('Correlation Between Yearly Export Values')
    plt.tight_layout()
    plt.show()

# Call the heatmap function
heatmap_correlation()

def aggregate_exports(countries, start_year, end_year):
    """
    Aggregate total exports for given countries over a specified period.

    Parameters:
    - countries: list of countries to aggregate exports for.
    - start_year: starting year (as a string, e.g., '2019').
    - end_year: ending year (as a string, e.g., '2022').

    Returns:
    - Total exports as a DataFrame.
    """
    selected_countries = df.loc[countries, start_year:end_year]

    total_exports = selected_countries.sum(axis=1)
    return total_exports

total_exports = aggregate_exports(['U S A', 'CAMEROON', 'GERMANY'], 'Year_2008_2009', 'Year_2014_2015')
print("Total Exports for Selected Countries Over Specified Period:")
print(total_exports)

def compare_country_growth(country1, country2):

    exports1 = df.loc[country1]
    exports2 = df.loc[country2]

    growth1 = exports1.pct_change() * 100
    growth2 = exports2.pct_change() * 100

    comparison_df = pd.DataFrame({
        'Year': exports1.index,
        country1: exports1.values,
        f'{country1} Growth (%)': growth1.values,
        country2: exports2.values,
        f'{country2} Growth (%)': growth2.values
    })

    return comparison_df

comparison_df = compare_country_growth('U S A', 'GEORGIA')
print("\nExport Growth Comparison Between USA and China:")
print(comparison_df)