# -*- coding: utf-8 -*-
"""model_teeth rayan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KH556m-7p6VOGkWTOZEgBnH--IOd-2DY

#این یک پروژه برای مسابقات رایان بود که ماسک برای عکس های دندان تولید میکنه ولی متاسفانه رم نمیکشه.

<font color='red'>**Changes in this version:**</font>



- These two lines in the dataset
```
self.image_paths = os.listdir(image_dir)[int(number_of_samples*split_ratio):]
self.mask_paths = os.listdir(mask_dir)[int(number_of_samples*split_ratio):]
```
Have been changed to:
```
self.image_paths = self.image_paths[int(number_of_samples*split_ratio):]
self.mask_paths = self.image_paths[int(number_of_samples*split_ratio):]
```

- The comment defining the mask output in the dataset, has been changed from
```
onehot_mask (torch.Tensor): One-hot encoded mask tensor for segmentation.
```
to
```
mask (torch.Tensor): Mask tensor for segmentation.
```

- `model` is transfered to `cpu` before saving the weights.

- There was a mistake in the previous update
```
self.mask_paths = self.image_paths[int(number_of_samples*split_ratio):]
```
has been changed to:
```
self.mask_paths = self.mask_paths[int(number_of_samples*split_ratio):]
```

<font color='red'>IMPORTANT</font>: The output of your model should be logits.

## Problem Definition

We are addressing a **semantic segmentation problem**, specifically focusing on **teeth caries CT scans**. The dataset contains **teeth scans** along with their corresponding **segmentation mask_paths**. The task involves segmenting the CT scan image_paths to accurately identify regions affected by caries.

The objective is to develop a model that can effectively segment the image_paths into the desired classes representing carious and non-carious regions. The challenge lies in optimizing the model's performance while managing memory constraints during training.

### Requirements:
- The model must be implemented using **`torch`** and **`torchvision`** only (no other deep learning libraries are allowed for the model architecture).
- The main class for the model must be named <font color='red'>**`Model`**</font>, and participants <font color='red'>**must not change this name**</font>.
- Do not change the init function inside the `Model` class.
- The size of your model must not exceed 70 MB.
- Instantiating your model must not require any parameters.

## Dataset

### Downloading the Teeth Dataset

First the dataset need to be downloaded.
"""

!pip install datasets tqdm -q
from huggingface_hub import login
from datasets import load_dataset
from huggingface_hub import snapshot_download
import os
import sys
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

dataset_id="RayanAi/Main_teeth_dataset"
# Set the local directory where you want to store the dataset
local_dataset_dir = "./Main_teeth_dataset"  # You can change this path to your desired location

# Create the directory if it doesn't exist
os.makedirs(local_dataset_dir, exist_ok=True)

# Suppress the output by redirecting it to os.devnull
with open(os.devnull, 'w') as fnull:
    # Save the original stdout
    original_stdout = sys.stdout
    try:
        # Redirect stdout to devnull to suppress output
        sys.stdout = fnull
        # Download the dataset and store it locally
        snapshot_download(repo_id=dataset_id, local_dir=local_dataset_dir, repo_type="dataset")
    finally:
        # Restore the original stdout
        sys.stdout = original_stdout

# Print message when download is complete
print("Dataset downloaded completely.")

# Calculate and print the total size of the downloaded files
total_size = 0
for dirpath, dirnames, filenames in os.walk(local_dataset_dir):
    for f in filenames:
        fp = os.path.join(dirpath, f)
        total_size += os.path.getsize(fp)

# Convert size to MB and print
print(f"Total size of downloaded files: {total_size / (1024 * 1024):.2f} MB")

# Get the absolute path of the dataset directory and print it
dataset_abs_path = os.path.abspath(local_dataset_dir)
print(f"Dataset has been saved at: [{dataset_abs_path}]")

!unzip -q ./Main_teeth_dataset/Main_teeth_dataset.zip -d ./Main_teeth_dataset/

"""### Handling Dataset"""

import os
import numpy as np
from PIL import Image
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset

import albumentations as A
from albumentations.pytorch import ToTensorV2
#Define the split ratio
split_ratio = 0.8

#Write a Dataset function called TeethSegmentationDataset
class TeethSegmentationDataset(Dataset):
    def __init__(self, image_dir: str, mask_dir: str, transform: A.Compose, dataset_type: str = 'Train', noisy_mask_paths: list = None):
        """
        Args:
            image_dir (str): Directory path containing input image_paths.
            mask_dir (str): Directory path containing corresponding segmentation mask_paths.
            transform (callable): Optional transformation to be applied to both the image and the mask. Use A.Compose. Use ToTensorV2()
            dataset_type (str, optional): Type of dataset, e.g., 'Train' or 'Test'. Defaults to 'Train'.
            noisy_mask_paths (list, optional): Provide a list of names for image_paths you want to be excluded from dataset
        """
        # Initialize paths and transformation
        self.image_dir = image_dir
        self.mask_dir = mask_dir
        self.transform = transform
        self.dataset_type = dataset_type

        # List of all image_paths and mask_paths
        self.image_paths = sorted(os.listdir(image_dir))
        self.mask_paths = sorted(os.listdir(mask_dir))
        # Filter out noisy mask_paths if provided
        if noisy_mask_paths:
            self.image_paths = [img for img in self.image_paths if img not in noisy_mask_paths]
            self.mask_paths = [mask for mask in self.mask_paths if mask not in noisy_mask_paths]
        number_of_samples = len(self.image_paths)

        if dataset_type == 'Train':
            self.image_paths = self.image_paths[:int(number_of_samples*split_ratio)]
            self.mask_paths = self.mask_paths[:int(number_of_samples*split_ratio)]
        elif dataset_type == 'Test':
            self.image_paths = self.image_paths[int(number_of_samples*split_ratio):]
            self.mask_paths = self.mask_paths[int(number_of_samples*split_ratio):]



    def __len__(self) -> int:

        return len(self.image_paths)


    def __getitem__(self, index: int) -> tuple[torch.Tensor, torch.Tensor]:

        try:
            image_path = os.path.join(self.image_dir, self.image_paths[index])
            mask_path = os.path.join(self.mask_dir, self.mask_paths[index])
        except (IOError, OSError) as e:
            print(f"Error opening image or mask: {e}")
            raise e
        # Load the image and mask
        image_path = os.path.join(self.image_dir, self.image_paths[index])
        mask_path = os.path.join(self.mask_dir, self.mask_paths[index])

        # Load image and mask as grayscale
        image = Image.open(image_path).convert("L")
        mask = Image.open(mask_path).convert("L")
        image = np.array(image)
        mask = np.array(mask)
        transformed = self.transform(image=image, mask=mask)
        image = transformed['image']
        mask = transformed['mask']
        binary_mask = mask.unsqueeze(2)>0
        binary_mask = binary_mask.permute(2, 0, 1).float()

        return image, binary_mask

######################augmenters######################
#You may want to alter this part
augmenter = A.Compose([
    A.HorizontalFlip(p=0.5),
    A.Rotate(limit=15, p=0.5),             # Random rotation within a small range
    A.ShiftScaleRotate(shift_limit=0.1, scale_limit=0.1, rotate_limit=15, p=0.5),
    A.RandomBrightnessContrast(p=0.2),
    A.GaussianBlur(p=0.1),                 # adds slight blurring
    A.Normalize(mean=(0.485,), std=(0.229,), max_pixel_value=255.0),
    ToTensorV2(),
])

######################################################

######################################################
#Don't touch this part
test_augmenter = A.Compose([
    A.Normalize(mean=(0.485,), std=(0.229,), max_pixel_value=255.0),
    ToTensorV2(),
])
######################################################

train_dataset = TeethSegmentationDataset(
    image_dir="/content/Main_teeth_dataset/images",
    mask_dir="./Main_teeth_dataset/labels",
    transform=augmenter,
    dataset_type='Train',

)

test_dataset = TeethSegmentationDataset(
    image_dir= "/content/Main_teeth_dataset/images",
    mask_dir="./Main_teeth_dataset/labels",
    transform=test_augmenter,
    dataset_type='Test',

)

from torch.utils.data import DataLoader
batch_size = 4  # dynamically gets the batch size

num_workers=2 # Increase this if you have a powerfull cpu
dataloaders = {
  'train': DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=num_workers),
  'test': DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=num_workers)
}
print(f"Train dataset size: {len(train_dataset)}")
print(f"Test dataset size: {len(test_dataset)}")

"""# Segmentation model
In this part you should design a segmentation model. If you have defined any functions used to define your model, you should upload it along the model code.

Your model shouldn't take any inputs or produce outputs when instantiating.

<font color='red'>Important: You can only use functions availble in `torch` and `torchvision`.</font>
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
class Model(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(Model, self).__init__()
        self.depthwise = nn.Conv2d(in_channels, in_channels, kernel_size=3, padding=1, groups=in_channels)
        self.pointwise = nn.Conv2d(in_channels, out_channels, kernel_size=1)
        self.bn = nn.BatchNorm2d(out_channels)
        self.relu = nn.ReLU(inplace=True)

    def forward(self, x):
        x = self.depthwise(x)
        x = self.pointwise(x)
        x = self.bn(x)
        return self.relu(x)


class DoubleConv(nn.Module):
    """Basic U-Net double convolution block."""
    def __init__(self, in_channels, out_channels):
        super(DoubleConv, self).__init__()
        self.double_conv = nn.Sequential(
            Model(in_channels, out_channels),
            Model(out_channels, out_channels)
        )

    def forward(self, x):
        return self.double_conv(x)


    #######DO NOT CHANGE THIS PART########
    def init(self):
        self.load_state_dict(torch.load('model.pth',weights_only=True))
    ######################################

class UNet(nn.Module):
    def __init__(self, in_channels=1, out_channels=1):
        super(UNet, self).__init__()

        # Encoder
        self.enc1 = DoubleConv(in_channels, 64)
        self.enc2 = DoubleConv(64, 128)
        self.enc3 = DoubleConv(128, 256)
        self.enc4 = DoubleConv(256, 512)

        # Bottleneck
        self.bottleneck = DoubleConv(512, 1024)

        # Decoder
        self.dec4 = DoubleConv(1024 + 512, 512)
        self.dec3 = DoubleConv(512 + 256, 256)
        self.dec2 = DoubleConv(256 + 128, 128)
        self.dec1 = DoubleConv(128 + 64, 64)

        # Final output layer
        self.out_conv = nn.Conv2d(64, out_channels, kernel_size=1)

        # Max pooling for downsampling
        self.max_pool = nn.MaxPool2d(kernel_size=2, stride=2)

    def forward(self, x):
        # Encoder path
        enc1 = self.enc1(x)
        enc2 = self.enc2(self.max_pool(enc1))
        enc3 = self.enc3(self.max_pool(enc2))
        enc4 = self.enc4(self.max_pool(enc3))

        # Bottleneck
        bottleneck = self.bottleneck(self.max_pool(enc4))

        # Decoder path
        dec4 = self.dec4(torch.cat([F.interpolate(bottleneck, scale_factor=2, mode='bilinear', align_corners=True), enc4], dim=1))
        dec3 = self.dec3(torch.cat([F.interpolate(dec4, scale_factor=2, mode='bilinear', align_corners=True), enc3], dim=1))
        dec2 = self.dec2(torch.cat([F.interpolate(dec3, scale_factor=2, mode='bilinear', align_corners=True), enc2], dim=1))
        dec1 = self.dec1(torch.cat([F.interpolate(dec2, scale_factor=2, mode='bilinear', align_corners=True), enc1], dim=1))

        # Output layer
        mask = self.out_conv(dec1)
        return mask
class DiceBCELoss(nn.Module):
    def __init__(self):
        super(DiceBCELoss, self).__init__()
        self.bce = nn.BCEWithLogitsLoss()

    def forward(self, logits, targets):
        # BCE Loss
        bce_loss = self.bce(logits, targets)

        # Dice Loss
        smooth = 1.0
        logits = torch.sigmoid(logits)
        intersection = (logits * targets).sum()
        dice_loss = 1 - (2. * intersection + smooth) / (logits.sum() + targets.sum() + smooth)

        return bce_loss + dice_loss

# Instantiate loss function
criterion = DiceBCELoss()

import torch
from torch.utils.data import DataLoader

# Define device: use GPU if available, else fall back to CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Assuming UNet model is already defined
model = UNet(in_channels=1, out_channels=1).to(device)

# Fetch a batch of image_paths from the DataLoader (assuming `dataloader` is already defined)
# Adjust the batch size if needed
dataloader = DataLoader(train_dataset, batch_size=4, shuffle=True, num_workers=2, pin_memory=True)

# Get a batch of image_paths and mask_paths
inputs, masked = next(iter(dataloader))

# Move inputs to the correct device
inputs = inputs.to(device)

# Perform a forward pass through the model
outputs = model(inputs)

# Set batch size dynamically from the input tensor
batch_size = inputs.shape[0]

# Assertions to ensure the dimensions match
assert inputs.shape == (batch_size, 1, 512, 512), "You shouldn't change the size of the input image"
assert outputs.shape == (batch_size, 1, 512, 512), "The output of your model does not have the correct dimensions"

# Print for debugging confirmation
print(f"Input shape: {inputs.shape}")
print(f"Output shape: {outputs.shape}")

"""## Dice Score

Here is the dice score function. You model is evaluated based on the score from this function
"""

def dice_score(pred: torch.Tensor, target_mask: torch.Tensor, epsilon: float = 1e-6) -> float:
    """
    Computes the Dice score between the predicted and target segmentation mask_paths.

    Args:
        pred (torch.Tensor): The predicted mask tensor, with values in range [0, 1].
        target_one_target_maskhot (torch.Tensor): The ground truth mask.
        epsilon (float, optional): A small value to avoid division by zero. Defaults to 1e-6.

    Returns:
        float: The Dice score, a similarity metric between 0 and 1.
    """
    pred = pred>0
    pred_flat = pred.contiguous().view(pred.shape[0], pred.shape[1], -1)
    target_flat = target_mask.contiguous().view(target_mask.shape[0], target_mask.shape[1], -1)

    intersection = (pred_flat * target_flat).sum(dim=-1)
    union = pred_flat.sum(dim=-1) + target_flat.sum(dim=-1)

    dice = (2. * intersection + epsilon) / (union + epsilon)

    dice_mean = dice.mean(dim=1)

    return dice_mean.mean()

"""## Training"""

import torch.optim as optim
from torch.optim.lr_scheduler import ReduceLROnPlateau
import matplotlib.pyplot as plt

# Optimizer and scheduler
optimizer = optim.Adam(model.parameters(), lr=1e-4)
scheduler = ReduceLROnPlateau(optimizer, mode='max', factor=0.5, patience=5, verbose=True)

import matplotlib.pyplot as plt
def visualize_mask(inputs: torch.Tensor, mask_paths: torch.Tensor, outputs: torch.Tensor):
    # Convert tensors to numpy for visualization
    sample_index = 0  # Index of the sample to visualize
    channel = 0
    print(f'Dice score is {dice_score(outputs[sample_index:sample_index+1,channel:channel+1],mask_paths[sample_index:sample_index+1,channel:channel+1])}')

    inputs_np = inputs.cpu().numpy()
    mask_paths_np = mask_paths.cpu().numpy()
    outputs_np = outputs.detach().cpu().numpy()

    # Choose a sample to visualize

    # Plotting
    plt.figure(figsize=(15, 5))

    plt.subplot(1, 3, 1)
    plt.imshow(inputs_np[sample_index].transpose(1, 2, 0), cmap='gray')  # Assuming inputs are in CxHxW format
    plt.title("Input Image")
    plt.axis('off')

    plt.subplot(1, 3, 2)
    plt.imshow(mask_paths_np[sample_index, channel], cmap='gray')  # Display the first channel of the mask
    plt.title("Ground Truth Mask")
    plt.axis('off')

    plt.subplot(1, 3, 3)
    plt.imshow(outputs_np[sample_index, channel]>0, cmap='gray')  # Display the first channel of the output
    plt.title("Model Output Mask")
    plt.axis('off')

    plt.show()

"""The `train_model` function implements a simple training loop that iterates over a specified number of epochs. In each iteration, the model is trained on the training set and then evaluated on the validation set using the Dice score as the performance metric. The function returns the model as it is at the final epoch."""

import torch
import time
import matplotlib.pyplot as plt
import torchvision
import torch.optim as optim
from torch.cuda.amp import autocast, GradScaler

model = model.to(device)  # Move model to GPU if available

# Training function with visualization support
def train_model(
    model: nn.Module,
    dataloaders: dict[str, DataLoader],
    criterion: nn.Module,
    optimizer: optim.Optimizer,
    num_epochs: int = 25
) -> nn.Module:
    """
    Trains the model over a specified number of epochs using the given data loaders,
    criterion (loss function), and optimizer.

    Args:
        model (nn.Module): The PyTorch model to be trained.
        dataloaders (dict[str, DataLoader]): A dictionary containing 'train' and 'test' data loaders.
        criterion (nn.Module): The loss function to be used for training.
        optimizer (torch.optim.Optimizer): The optimizer used to adjust model parameters.
        num_epochs (int, optional): Number of epochs for training. Defaults to 25.

    Returns:
        nn.Module: The trained model.
    """
    since = time.time()

    train_losses = []
    test_losses = []
    dice_scores_epoch = []
    scaler = GradScaler()
    for epoch in range(num_epochs):
        dice_scores = []
        print(f'Epoch {epoch}/{num_epochs-1}')
        print('-' * 10)

        # Each epoch has a training and validation phase
        for phase in ['train', 'test']:
            if phase == 'train':
                model.train()  # Set model to training mode
            else:
                model.eval()   # Set model to evaluate mode

            running_loss = 0.0

            # Iterate over data
            for inputs, mask_paths in dataloaders[phase]:
                inputs = inputs.to(device)
                mask_paths = mask_paths.to(device)
                with autocast():  # Enable autocasting for mixed precision
                    outputs = model(inputs)
                    loss = criterion(outputs, mask_paths)
                # Zero the parameter gradients
                optimizer.zero_grad()

                # Forward
                with torch.set_grad_enabled(phase == 'train'):
                    outputs = model(inputs)

                    loss = criterion(outputs,mask_paths)

                    # Backward + optimize only if in training phase
                    if phase == 'train':
                        scaler.scale(loss).backward()
                        scaler.step(optimizer)
                        scaler.update()
                        loss.backward()
                        optimizer.step()
                    else:
                        dice_scores.append(dice_score(outputs, mask_paths))

                # Statistics
                running_loss += loss.item() * inputs.size(0)

            epoch_loss = running_loss / len(dataloaders[phase].dataset)
            if phase == 'train':
                train_losses.append(epoch_loss)
            else:
                test_losses.append(epoch_loss)
                dice_scores_epoch.append(torch.tensor(dice_scores).mean().item())

                visualize_mask(inputs, mask_paths, outputs)


            print(f'{phase} Loss: {epoch_loss:.4f}')
            if phase == 'test':
                print(f'Dice score: {torch.tensor(dice_scores).mean()}')

    time_elapsed = time.time() - since
    print(f'Training complete in {time_elapsed // 60:.0f}m {time_elapsed % 60:.0f}s')

    # Plot the results
    epochs_range = range(num_epochs)
    plt.figure(figsize=(10, 5))

    plt.subplot(1, 2, 1)
    plt.plot(epochs_range, train_losses, label="Train Loss")
    plt.plot(epochs_range, test_losses, label="Test Loss")
    plt.legend(loc="upper right")
    plt.title("Training and Test Loss")

    plt.subplot(1, 2, 2)
    plt.plot(epochs_range, dice_scores_epoch, label="Dice Score", color="green")
    plt.legend(loc="lower right")
    plt.title("Dice Score")

    plt.show()

    return model

# Train the model
model = train_model(model, dataloaders, criterion, optimizer)

model_save_path = "model.pth"
torch.save(model.cpu().state_dict(), model_save_path)