# -*- coding: utf-8 -*-
"""Podcast_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lmC7kakm-4qQ-5KfP7-pp2nMaPKh7wlK

#در این پروژه با از لینک پادکست های دیتاست وب اسکرپینگ انجام میدیم و بعد با توجه به موضوعات و تاریخ و نوع پادکست یک دسته بندی درست میکنیم مرتبط با موضوع یه الگوریتم روش ست میکنیم  

# Data set name is : podcasts_en
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

file = 'podcasts_en.xlsx'
df = pd.read_excel(file)

df

df.info()

df.dropna(inplace=True)
df.reset_index(drop=True, inplace=True)

df.info()

df['language'].unique()

cat_set = set()

for i in range(df.shape[0]):
  cats = df['categories'][i].split(',')
  for c in cats:
    cat_set.add(c)

cat_df = {c:[] for c in cat_set}
for i in range(df.shape[0]):
  cats = df['categories'][i].split(',')
  for k in cat_df.keys():
    if c in cats:
      cat_df[k].append(1)
    else:
      cat_df[k].append(0)
cat_df = pd.DataFrame(cat_df)

cat_df

cat_url = df['rss_link']
cat_url = cat_url[cat_url.str.len() <=80]
cat_url.reset_index(drop=True, inplace=True)

cat_url = cat_url[:20]
cat_url

import requests
from bs4 import BeautifulSoup
from bs4 import XMLParsedAsHTMLWarning
import warnings

import requests
from bs4 import BeautifulSoup

not_good = []
url_good = []

import requests
import xml.etree.ElementTree as ET

all_data = []
def url_get(url):
    items = []
    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()

        if response.status_code == 200:
            xml_content = response.text
            root = ET.fromstring(response.content)
            for it in root.findall('.//item'):
                dit_info = {'title' : it.findtext('title'),
                           'description': it.findtext('description'),
                            'summary': it.findtext('description'),
                            'publiciti': it.findtext('pubDate')}
                items.append(dit_info)
    except requests.exceptions.RequestException as e:
        print(f"Error fetching {url}: {e}")
        not_good.append(url)



    return items
data_url = []
for url in cat_url:
  data = url_get(url)
  data_url.append(data)
data_url = pd.DataFrame(data_url)

data_url

data_url.info()

not_good_indices = [index for index, url in enumerate(cat_url) if url in not_good]
data_url.drop(not_good_indices,inplace=True)

df_droped = data_url

df_droped['non_null_count'] = df_droped.apply(lambda row: row.count(), axis=1)

df_filtered = df_droped[df_droped['non_null_count'] >= 100]

df_filtered = df_filtered.drop(columns=['non_null_count'])

gone_after_filtered = df_droped[~df_droped.index.isin(df_filtered.index)]

removed_indices = gone_after_filtered.index.tolist()

removed_indices
total_removed = []
total_removed.extend(removed_indices)
total_removed.extend(not_good_indices)
total_removed

df_droped

df_drop = df_filtered.dropna(axis=1, how='any')
df_drop.reset_index(drop=True, inplace=True)

outcomes_url = df_drop.copy()
outcomes_url.to_string
outcomes_url.info()

outcomes_url

def concatenate_text(row):
    text_list = []
    for col in outcomes_url.columns:
        if col in row:
            item = row[col]
            if isinstance(item, dict):
                text_items = []
                if 'title' in item and item['title'] is not None:
                    text_items.append(str(item['title']))
                if 'description' in item and item['description'] is not None:
                    text_items.append(str(item['description']))
                if 'summary' in item and item['summary'] is not None:
                    text_items.append(str(item['summary']))
                if 'publiciti' in item and item['publiciti'] is not None:
                    text_items.append(str(item['publiciti']))
                if text_items:
                    text_list.append(' '.join(text_items))

    return ' '.join(text_list)
outcomes_url['text_data'] = outcomes_url.apply(concatenate_text, axis=1)

print(outcomes_url)

df_need = df[['podcast_name', 'rss_link', 'language', 'categories']]
df_need.drop(total_removed, inplace=True)
df_need = df_need.reset_index(drop=True)

needed_data = pd.concat([df_need, outcomes_url['text_data']], axis=1)

needed_data

import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    tokens = word_tokenize(text)
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
    return ' '.join(tokens)

corpus = outcomes_url['text_data']

preprocessed_corpus = [preprocess_text(doc) for doc in corpus]
print("Preprocessed Corpus:")
print(preprocessed_corpus)

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(preprocessed_corpus)
tfidf_array = tfidf_matrix.toarray()
feature_names = vectorizer.get_feature_names_out()

from sklearn.cluster import KMeans

num_clusters = 2

kmeans = KMeans(n_clusters=num_clusters, random_state=42)

kmeans.fit(tfidf_matrix)

kmeans_labels = kmeans.labels_

print("K-Means Cluster Labels:")
print(kmeans_labels)

from sklearn.cluster import DBSCAN

dbscan = DBSCAN(eps=0.5, min_samples=2)

dbscan.fit(tfidf_matrix)

dbscan_labels = dbscan.labels_

print("DBSCAN Cluster Labels:")
print(dbscan_labels)

from sklearn.cluster import AgglomerativeClustering

num_clusters = 2

hierarchical = AgglomerativeClustering(n_clusters=num_clusters)

hierarchical_labels = hierarchical.fit_predict(tfidf_array)

print("Hierarchical Cluster Labels:")
print(hierarchical_labels)

from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score

def evaluate_clustering(labels, features):
    if len(set(labels)) > 1:
        silhouette = silhouette_score(features, labels)
        davies_bouldin = davies_bouldin_score(features, labels)
        calinski_harabasz = calinski_harabasz_score(features, labels)
        return silhouette, davies_bouldin, calinski_harabasz
    else:
        return None, None, None

kmeans_silhouette, kmeans_db, kmeans_ch = evaluate_clustering(kmeans_labels, tfidf_array)
print("K-Means Evaluation:")
print(f"Silhouette Score: {kmeans_silhouette}")
print(f"Davies-Bouldin Index: {kmeans_db}")
print(f"Calinski-Harabasz Index: {kmeans_ch}")

dbscan_silhouette, dbscan_db, dbscan_ch = evaluate_clustering(dbscan_labels, tfidf_array)
print("\nDBSCAN Evaluation:")
print(f"Silhouette Score: {dbscan_silhouette}")
print(f"Davies-Bouldin Index: {dbscan_db}")
print(f"Calinski-Harabasz Index: {dbscan_ch}")

hierarchical_silhouette, hierarchical_db, hierarchical_ch = evaluate_clustering(hierarchical_labels, tfidf_array)
print("\nHierarchical Clustering Evaluation:")
print(f"Silhouette Score: {hierarchical_silhouette}")
print(f"Davies-Bouldin Index: {hierarchical_db}")
print(f"Calinski-Harabasz Index: {hierarchical_ch}")

